spring:
  datasource:
    username: root
    password: mysql@726
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true  


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
